<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-I6T4BAQ" name="runner.TestRunner" tests="1" failures="1" timestamp="20 Jul 2020 03:14:01 GMT" time="8.122" errors="0">
  <testcase name="runScenario" time="8.122" classname="runner.TestRunner">
    <failure type="java.lang.AssertionError" message="expected [4] but found [Display is 1]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [Display is 1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at core.WinniumSteps.verifyResult(WinniumSteps.java:40)
	at âœ½.I validate the result as "4" in calculator(file:///C:/Users/Gokul/workspace/clarivate/src/test/resources/feature/desktop/Calculator.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- runner.TestRunner -->
